apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: search-backend
  annotations:
    run.googleapis.com/launch-stage: BETA
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
    spec:
      serviceAccountName: ${SERVICE_ACCOUNT}
      containers:
      - name: backend
        image: ${BACKEND_IMAGE}
        ports:
        - containerPort: 8080
        env:
        - name: GCP_PROJECT_ID
          value: "${PROJECT_ID}"
        - name: GCP_LOCATION
          value: "${REGION}"

        - name: INSTANCE_CONNECTION_NAME
          value: "${INSTANCE_CONNECTION_NAME}"
        - name: VERTEX_SEARCH_DATA_STORE_ID
          value: "${VERTEX_SEARCH_DATA_STORE_ID}"
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: DB_USER
          value: "${DB_USER}"
        - name: DB_NAME
          value: "${DB_NAME}"
        - name: DB_PASSWORD
          value: "${DB_PASSWORD}"
      - name: auth-proxy
        image: gcr.io/alloydb-connectors/alloydb-auth-proxy:latest
        args:
        - "${INSTANCE_CONNECTION_NAME}"
        - "--address=127.0.0.1"
        - "--port=5432"
        - "--public-ip"
        # - "--credential-file=/secrets/key.json" # If using specific credentials
        resources:
          limits:
            cpu: "1000m"
            memory: "512Mi"
